apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
  type: NodePort # Using NodePort for simplicity, in a real cloud setup you might use LoadBalancer