apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
spec:
  replicas: 1 # Default replica count
  selector:
    matchLabels:
      app: redis
      role: follower
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: follower
        tier: backend
    spec:
      containers:
      - name: follower
        image: registry.k8s.io/google-samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: dns