apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: guestbook-prod

resources:
  - namespace.yaml

patchesStrategicMerge:
  - frontend-deployment-patch.yaml